# Amazon Customer Data Cleaning & Feature Engineering

## Introduction

Data quality is an important part of any data analysis project because inaccurate, inconsistent, or incomplete data can lead to unreliable business insights.

In this project, the Amazon customer order dataset is prepared for further analysis by systematically inspecting the raw data, identifying potential data-quality issues, validating existing calculations, converting fields into appropriate data types, and creating useful analytical features.

The goal of this notebook is to transform the raw dataset into a **clean, validated, and analysis-ready dataset** that can later be used for exploratory analysis, SQL analysis, and Excel reporting.

This notebook represents the **data preparation stage** of the overall Amazon Customer Analytics project.

### Objectives

* Understand the structure and characteristics of the raw dataset
* Identify missing and duplicate records
* Check for invalid or inconsistent values
* Convert columns to appropriate data types
* Validate existing calculations
* Create additional business-related features
* Perform final data-quality validation
* Prepare the dataset for downstream analysis

## Project Overview

This notebook focuses on cleaning, validating, and preparing Amazon customer order data for further analysis.

The objective is to ensure that the dataset is accurate, consistent, and analysis-ready by performing data quality checks, validating existing fields, creating derived business metrics, and organizing the final dataset.

### Tools & Technologies

* **Python**
* **Pandas** — Data manipulation and cleaning
* **NumPy** — Numerical calculations and validation
* **Jupyter Notebook** — Analysis environment

### Key Activities

1. Load and inspect the raw dataset
2. Check data types and dataset structure
3. Identify missing values
4. Check for duplicate records
5. Validate numerical and categorical values
6. Convert date fields into appropriate data types
7. Validate calculated values
8. Create new analytical features
9. Perform final data-quality checks
10. Prepare the cleaned dataset for further analysis

## Dataset Description

The dataset contains Amazon customer order information that can be used to analyze customer purchasing behavior, order values, discounts, and sales performance.

The notebook works with the following types of information:

* Customer information
* Product/order information
* Order dates
* Quantity
* Pricing information
* Discount information
* Order and sales-related metrics

The raw dataset is loaded into a Pandas DataFrame and inspected before any transformation is performed.

In [1]:
import pandas as pd
import numpy as np

## Data quality check

Several data-quality checks are performed to determine whether the dataset contains issues that could affect downstream analysis.

### Missing Values

The dataset is checked for missing or null values across all columns.

### Duplicate Records

Duplicate records are identified to ensure that the same order/customer record is not unintentionally represented multiple times.

### Invalid Values

Relevant numerical and categorical fields are checked for invalid or unexpected values.

These checks help establish whether the raw dataset is suitable for further analysis and identify areas requiring attention.

Check for missing values

In [2]:
df = pd.read_csv("Amazon (1).csv")

In [3]:
df_copy = df.copy()

In [4]:
df_copy.head(5)

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411

In [5]:
df_copy.isnull().sum()

OrderID          0
OrderDate        0
CustomerID       0
CustomerName     0
ProductID        0
ProductName      0
Category         0
Brand            0
Quantity         0
UnitPrice        0
Discount         0
Tax              0
ShippingCost     0
TotalAmount      0
PaymentMethod    0
OrderStatus      0
City             0
State            0
Country          0
SellerID         0
dtype: int64

Check for duplicates

In [6]:
df_copy.duplicated().sum()

np.int64(0)

In [7]:
df_copy[df_copy.duplicated(keep=False)]

Empty DataFrame
Columns: [OrderID, OrderDate, CustomerID, CustomerName, ProductID, ProductName, Category, Brand, Quantity, UnitPrice, Discount, Tax, ShippingCost, TotalAmount, PaymentMethod, OrderStatus, City, State, Country, SellerID]
Index: []

Check for invalid values

In [8]:
df_copy[df_copy["Quantity"] <=0 ];

In [9]:
df_copy[df_copy["UnitPrice"] <= 0]

Empty DataFrame
Columns: [OrderID, OrderDate, CustomerID, CustomerName, ProductID, ProductName, Category, Brand, Quantity, UnitPrice, Discount, Tax, ShippingCost, TotalAmount, PaymentMethod, OrderStatus, City, State, Country, SellerID]
Index: []

In [10]:
df_copy[df_copy["Discount"] < 0]

Empty DataFrame
Columns: [OrderID, OrderDate, CustomerID, CustomerName, ProductID, ProductName, Category, Brand, Quantity, UnitPrice, Discount, Tax, ShippingCost, TotalAmount, PaymentMethod, OrderStatus, City, State, Country, SellerID]
Index: []

In [11]:
df_copy[df_copy["Discount"] > 1]

Empty DataFrame
Columns: [OrderID, OrderDate, CustomerID, CustomerName, ProductID, ProductName, Category, Brand, Quantity, UnitPrice, Discount, Tax, ShippingCost, TotalAmount, PaymentMethod, OrderStatus, City, State, Country, SellerID]
Index: []

In [12]:
df_copy[df_copy["Tax"] < 0]

Empty DataFrame
Columns: [OrderID, OrderDate, CustomerID, CustomerName, ProductID, ProductName, Category, Brand, Quantity, UnitPrice, Discount, Tax, ShippingCost, TotalAmount, PaymentMethod, OrderStatus, City, State, Country, SellerID]
Index: []

In [13]:
df_copy[df_copy["ShippingCost"] < 0]

Empty DataFrame
Columns: [OrderID, OrderDate, CustomerID, CustomerName, ProductID, ProductName, Category, Brand, Quantity, UnitPrice, Discount, Tax, ShippingCost, TotalAmount, PaymentMethod, OrderStatus, City, State, Country, SellerID]
Index: []

In [14]:
df_copy[df_copy["TotalAmount"] < 0]

Empty DataFrame
Columns: [OrderID, OrderDate, CustomerID, CustomerName, ProductID, ProductName, Category, Brand, Quantity, UnitPrice, Discount, Tax, ShippingCost, TotalAmount, PaymentMethod, OrderStatus, City, State, Country, SellerID]
Index: []

## Data Type Conversion

The `OrderDate` column is converted into an appropriate datetime format.

Proper date formatting is important because it allows the dataset to support time-based analysis such as:

* Yearly analysis
* Monthly analysis
* Order trends over time
* Period-based comparisons

Correct data types also improve the reliability of subsequent calculations and transformations.

In [15]:
df_copy.dtypes

OrderID              str
OrderDate            str
CustomerID           str
CustomerName         str
ProductID            str
ProductName          str
Category             str
Brand                str
Quantity           int64
UnitPrice        float64
Discount         float64
Tax              float64
ShippingCost     float64
TotalAmount      float64
PaymentMethod        str
OrderStatus          str
City                 str
State                str
Country              str
SellerID             str
dtype: object

In [16]:
df_copy["OrderDate"] = pd.to_datetime(df_copy["OrderDate"])

In [17]:
df_copy.dtypes

OrderID                     str
OrderDate        datetime64[us]
CustomerID                  str
CustomerName                str
ProductID                   str
ProductName                 str
Category                    str
Brand                       str
Quantity                  int64
UnitPrice               float64
Discount                float64
Tax                     float64
ShippingCost            float64
TotalAmount             float64
PaymentMethod               str
OrderStatus                 str
City                        str
State                       str
Country                     str
SellerID                    str
dtype: object

In [18]:
df_copy.head(5)

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,Discount,Tax,ShippingCost,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,0.00,0.00,0.09,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,0.05,19.10,1.74,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,3,35.03,0.10,7.57,5.91,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,5,33.58,0.15,11.42,5.53,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,2,515.64,0.25,38.67,9.23,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411

## Calculation Validation

Existing numerical calculations in the dataset are validated to ensure that derived values are mathematically consistent with their underlying fields.

Numerical comparisons are performed using NumPy's `isclose()` function where appropriate.

This helps identify discrepancies caused by:

* Incorrect calculations
* Rounding differences
* Data-entry issues
* Inconsistent values

Only after validation is the dataset used for further feature engineering.

Folmula:

Quantity * UnitPrice *(1-Discount) + tax + ShippingCost = TotalAmount

In [19]:
diff = (df_copy["Quantity"]*df_copy["UnitPrice"]*(1-df_copy["Discount"])+df_copy["Tax"]+df_copy["ShippingCost"])-df_copy["TotalAmount"]
mask = (~np.isclose(diff,0,atol=0.01))
print(mask.sum())

0

In [20]:
df_copy.loc[mask,["Quantity","UnitPrice","Discount","Tax","ShippingCost","TotalAmount"]].head(10)

Empty DataFrame
Columns: [Quantity, UnitPrice, Discount, Tax, ShippingCost, TotalAmount]
Index: []

## Feature Engineering

New analytical features are created from the existing dataset to make the data more useful for business analysis.

### GrossAmount

Represents the order value before applying discounts.

### DiscountedAmount

Represents the discount-related amount calculated from the available pricing and discount information.

### NetAmount

Represents the final order value after considering the applicable discount.

### OrderYear

Extracted from `OrderDate` to support yearly analysis.

### OrderMonth

Extracted from `OrderDate` to support monthly analysis.

These engineered features will make it easier to answer business questions related to sales, discounts, customer behavior, and order trends.

In [ ]:
#Creating Gross Amount
df_copy["GrossAmount"] = (df_copy["Quantity"]*df_copy["UnitPrice"]).round(2)
df_copy["GrossAmount"].head(5)

0     319.77
1     251.37
2     105.09
3     167.90
4    1031.28
Name: GrossAmount, dtype: float64

In [ ]:
#Creating Discounted Amount
df_copy["DiscountedAmount"] = (df_copy["GrossAmount"]*df_copy["Discount"]).round(2)
df_copy["DiscountedAmount"].head(10)

0      0.00
1     12.57
2     10.51
3     25.18
4    257.82
5      0.00
6     87.92
7     30.65
8      0.00
9     55.64
Name: DiscountedAmount, dtype: float64

In [26]:
#Creating Net Amount
df_copy["NetAmount"] = (df_copy["GrossAmount"]-df_copy["DiscountedAmount"])
df_copy["NetAmount"]

0         319.77
1         238.80
2          94.58
3         142.72
4         773.46
          ...
99995     984.68
99996    2246.50
99997     929.60
99998     294.05
99999     791.82
Name: NetAmount, Length: 100000, dtype: float64

In [30]:
##Creating Order Year
df_copy["OrderYear"] = df_copy["OrderDate"].dt.year
df_copy["OrderYear"]

0        2023
1        2023
2        2022
3        2023
4        2023
         ...
99995    2023
99996    2021
99997    2023
99998    2021
99999    2021
Name: OrderYear, Length: 100000, dtype: int32

In [32]:
##Creating Order Month
df_copy["OrderMonth"] = df_copy["OrderDate"].dt.month_name()
df_copy["OrderMonth"]

0         January
1        December
2             May
3            July
4        February
           ...
99995       March
99996    November
99997       April
99998    November
99999    December
Name: OrderMonth, Length: 100000, dtype: str

In [33]:
df_copy.head(2)

,OrderID,OrderDate,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,Quantity,UnitPrice,...,OrderStatus,City,State,Country,SellerID,GrossAmount,DiscountedAmount,NetAmount,OrderYear,OrderMonth
0,ORD0000001,2023-01-31,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,3,106.59,...,Delivered,Washington,DC,India,SELL01967,319.77,0.00,319.77,2023,January
1,ORD0000002,2023-12-30,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,1,251.37,...,Delivered,Fort Worth,TX,United States,SELL01298,251.37,12.57,238.80,2023,December

## Reorganize the columns

In [34]:
cols = df_copy.columns.tolist()
for c in ["OrderYear","OrderMonth","GrossAmount","DiscountedAmount","NetAmount"]:
    cols.remove(c)
idx = cols.index("OrderDate")+1
cols[idx:idx] = ["OrderYear","OrderMonth"]

idx = cols.index("TotalAmount")
cols[idx:idx] = ["GrossAmount","DiscountedAmount","NetAmount"]
df_copy = df_copy[cols]

## Final Data Validation

After cleaning and feature engineering, the resulting DataFrame is checked again to ensure that the transformations have not introduced new data-quality issues.

The final validation includes checks for:

* Missing values
* Duplicate records
* Data types
* Derived features
* Overall dataset structure

The final dataset is intended to be clean, consistent, and ready for downstream analysis using Python, SQL, and Excel.

In [36]:
df_copy.head(10)

,OrderID,OrderDate,OrderYear,OrderMonth,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,...,GrossAmount,DiscountedAmount,NetAmount,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,2023,January,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,...,319.77,0.00,319.77,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,2023,December,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,...,251.37,12.57,238.80,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,2022,May,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,...,105.09,10.51,94.58,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,2023,July,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,...,167.90,25.18,142.72,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,2023,February,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,...,1031.28,257.82,773.46,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411
5,ORD0000006,2022-12-31,2022,December,CUST042705,Karan Sharma,P00023,Cookware Set,Books,ReadMore,...,1798.92,0.00,1798.92,2017.53,UPI,Delivered,Los Angeles,CA,United States,SELL01494
6,ORD0000007,2024-09-20,2024,September,CUST037667,Aarav Verma,P00030,Dress Shirt,Clothing,UrbanStyle,...,439.62,87.92,351.70,394.81,UPI,Delivered,Chicago,IL,Australia,SELL01676
7,ORD0000008,2022-11-10,2022,November,CUST031165,Rohit Kumar,P00028,Jeans,Toys & Games,KiddoFun,...,613.02,30.65,582.37,617.73,Debit Card,Pending,Denver,CO,India,SELL00510
8,ORD0000009,2024-06-26,2024,June,CUST026965,Aman Kapoor,P00031,Kids Toy Car,Sports & Outdoors,Apex,...,584.36,0.00,584.36,638.14,Debit Card,Delivered,Washington,DC,United States,SELL01895
9,ORD0000010,2020-05-01,2020,May,CUST029472,Aarav Reddy,P00001,Wireless Earbuds,Clothing,Apex,...,556.42,55.64,500.78,565.75,Credit Card,Delivered,Houston,TX,United States,SELL01584

In [37]:
df_copy.isna().sum()

OrderID             0
OrderDate           0
OrderYear           0
OrderMonth          0
CustomerID          0
CustomerName        0
ProductID           0
ProductName         0
Category            0
Brand               0
Quantity            0
UnitPrice           0
Discount            0
Tax                 0
ShippingCost        0
GrossAmount         0
DiscountedAmount    0
NetAmount           0
TotalAmount         0
PaymentMethod       0
OrderStatus         0
City                0
State               0
Country             0
SellerID            0
dtype: int64

In [39]:
df_copy = df_copy.to_csv("Amazon_cleaned.csv",index=False)

In [40]:
# Verify saved dataset
cleaned_df = pd.read_csv("Amazon_cleaned.csv")

print(f"Dataset saved successfully: {cleaned_df.shape}")
cleaned_df.head()

Dataset saved successfully: (100000, 25)

,OrderID,OrderDate,OrderYear,OrderMonth,CustomerID,CustomerName,ProductID,ProductName,Category,Brand,...,GrossAmount,DiscountedAmount,NetAmount,TotalAmount,PaymentMethod,OrderStatus,City,State,Country,SellerID
0,ORD0000001,2023-01-31,2023,January,CUST001504,Vihaan Sharma,P00014,Drone Mini,Books,BrightLux,...,319.77,0.00,319.77,319.86,Debit Card,Delivered,Washington,DC,India,SELL01967
1,ORD0000002,2023-12-30,2023,December,CUST000178,Pooja Kumar,P00040,Microphone,Home & Kitchen,UrbanStyle,...,251.37,12.57,238.80,259.64,Amazon Pay,Delivered,Fort Worth,TX,United States,SELL01298
2,ORD0000003,2022-05-10,2022,May,CUST047516,Sneha Singh,P00044,Power Bank 20000mAh,Clothing,UrbanStyle,...,105.09,10.51,94.58,108.06,Debit Card,Delivered,Austin,TX,United States,SELL00908
3,ORD0000004,2023-07-18,2023,July,CUST030059,Vihaan Reddy,P00041,Webcam Full HD,Home & Kitchen,Zenith,...,167.90,25.18,142.72,159.66,Cash on Delivery,Delivered,Charlotte,NC,India,SELL01164
4,ORD0000005,2023-02-04,2023,February,CUST048677,Aditya Kapoor,P00029,T-Shirt,Clothing,KiddoFun,...,1031.28,257.82,773.46,821.36,Credit Card,Cancelled,San Antonio,TX,Canada,SELL01411

## Conclusion

The Amazon customer dataset has been systematically inspected, validated, cleaned, and enhanced with additional analytical features.

The resulting dataset provides a reliable foundation for the next stages of the project, including:

* Exploratory Data Analysis using Python
* SQL-based business analysis
* Excel-based reporting and visualization
* Customer and sales performance analysis

This notebook represents the **data preparation stage** of the overall Amazon Customer Analytics project.